from __future__ import annotations

import shutil
from pathlib import Path

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse, Response

from app.config import NOVELS_ROOT
from app.constants import STATUS_ORDER
from app.db import get_conn
from app.deps import get_templates
from app.security import require_auth
from app.services.chapter_service import write_markdown
from app.services.library_service import list_chapters, scan_projects
from app.services.metrics_service import get_project_stats, log_operation
from app.services.path_service import chapter_path, project_path
from app.services.project_service import set_project_meta
from app.services.markdown_service import safe_slug

router = APIRouter()


@router.post("/examples/create", response_class=HTMLResponse)
def create_example_project(request: Request) -> Response:
    require_auth(request)
    project = "DemoProject"
    root = project_path(project)
    if not root.exists():
        (root / "chapters").mkdir(parents=True, exist_ok=True)
        (root / "characters").mkdir(parents=True, exist_ok=True)
        (root / "world").mkdir(parents=True, exist_ok=True)
        log_operation("create_project", project)

        # Add sample chapter
        path = chapter_path(project, "001-demo-chapter")
        frontmatter = {
            "title": "Welcome to Novel Hub",
            "chapter": "1",
            "status": "draft",
            "volume": "",
            "tags": [],
            "synopsis": "",
            "notes": "",
            "pov": "",
            "characters": [],
            "locations": [],
            "warnings": [],
            "draft_version": "v1",
        }
        write_markdown(
            path,
            frontmatter,
            "This is a demo chapter generated by the system. You can start typing your story here!",
        )
        log_operation("create_chapter", str(path))

    return RedirectResponse(url=f"/projects/{project}", status_code=303)


@router.get("/projects", response_class=HTMLResponse)
def projects_page(request: Request) -> Response:
    if not request.session.get("authed"):
        return RedirectResponse("/login", status_code=303)
    templates = get_templates()
    return templates.TemplateResponse(
        "projects.html", {"request": request, "projects": scan_projects()}
    )


@router.post("/projects/new", response_class=HTMLResponse)
def create_project(request: Request, name: str = Form(...)) -> Response:
    require_auth(request)
    project = safe_slug(name, fallback="MyNovel")
    root = project_path(project)
    (root / "chapters").mkdir(parents=True, exist_ok=True)
    (root / "characters").mkdir(parents=True, exist_ok=True)
    (root / "world").mkdir(parents=True, exist_ok=True)
    log_operation("create_project", project)
    return RedirectResponse(url=f"/projects/{project}", status_code=303)


@router.delete("/projects/{project}")
def delete_project(request: Request, project: str) -> Response:
    require_auth(request)
    safe_project = safe_slug(project, fallback="project")
    p = project_path(safe_project)
    if p.exists():
        shutil.rmtree(p)
        with get_conn() as conn:
            conn.execute("DELETE FROM file_index WHERE project=?", (safe_project,))
            conn.execute("DELETE FROM chapter_fts WHERE project=?", (safe_project,))
            conn.execute("DELETE FROM project_meta WHERE project=?", (safe_project,))
        log_operation("delete_project", safe_project, project=safe_project)
    return JSONResponse(content={"status": "ok"})


@router.put("/projects/{project}/rename")
async def rename_project(request: Request, project: str) -> Response:
    require_auth(request)
    data = await request.json()
    new_name = safe_slug(data.get("name", ""), fallback="project")
    if not new_name:
        raise HTTPException(status_code=400)

    safe_project = safe_slug(project, fallback="project")
    old_p = project_path(safe_project)
    new_p = NOVELS_ROOT / new_name

    if new_p.exists():
        raise HTTPException(status_code=400, detail="Project already exists")

    if old_p.exists():
        old_p.rename(new_p)
        with get_conn() as conn:
            rows = conn.execute(
                "SELECT path FROM file_index WHERE project=?", (safe_project,)
            ).fetchall()
            for r in rows:
                old_path = r["path"]
                new_path_str = old_path.replace(str(old_p), str(new_p), 1)
                conn.execute(
                    "UPDATE file_index SET path=?, project=? WHERE path=?",
                    (new_path_str, new_name, old_path),
                )
                conn.execute(
                    "UPDATE chapter_fts SET path=?, project=? WHERE path=?",
                    (new_path_str, new_name, old_path),
                )

            conn.execute(
                "UPDATE project_meta SET project=? WHERE project=?",
                (new_name, safe_project),
            )
        log_operation("rename_project", f"{project} -> {new_name}", project=new_name)

    return JSONResponse(
        content={"status": "ok", "new_url": f"/projects/{new_name}"}
    )


@router.get("/projects/{project}", response_class=HTMLResponse)
def project_detail(
    request: Request, project: str, status: str | None = None
) -> Response:
    if not request.session.get("authed"):
        return RedirectResponse("/login", status_code=303)
    safe_project = safe_slug(project, fallback="project")
    project_info = next(
        (p for p in scan_projects() if p["name"] == safe_project), None
    )
    if not project_info:
        raise HTTPException(status_code=404, detail="project not found")

    # T3.4 Calculate C-Route Stats
    with get_conn() as conn:
        counts = conn.execute(
            """SELECT
               COUNT(CASE WHEN kind='character' THEN 1 END) as character_count,
               COUNT(CASE WHEN kind='location' THEN 1 END) as location_count,
               COUNT(CASE WHEN kind='thread' THEN 1 END) as thread_count
               FROM entities WHERE project=?""",
            (safe_project,),
        ).fetchone()

        project_info["character_count"] = counts["character_count"]
        project_info["location_count"] = counts["location_count"]
        project_info["thread_count"] = counts["thread_count"]

    chapters = list_chapters(safe_project)
    if status and status in STATUS_ORDER:
        chapters = [c for c in chapters if c["status"] == status]
    recent = sorted(chapters, key=lambda x: x["modified"], reverse=True)[:5]

    # T1.6: Volume sync
    p_path = project_path(safe_project) / "chapters"
    volumes = []
    if p_path.exists():
        physical_volumes = [
            d.name
            for d in p_path.iterdir()
            if d.is_dir() and not d.name.startswith(".")
        ]
        with get_conn() as conn:
            for slug in physical_volumes:
                conn.execute(
                    "INSERT OR IGNORE INTO volumes (project, slug, title, seq) VALUES (?, ?, ?, ?)",
                    (safe_project, slug, slug, 0),
                )
            rows = conn.execute(
                "SELECT * FROM volumes WHERE project=? ORDER BY seq", (safe_project,)
            ).fetchall()
            volumes = [dict(r) for r in rows]

    templates = get_templates()
    return templates.TemplateResponse(
        "project_detail.html",
        {
            "request": request,
            "project": safe_project,
            "project_info": project_info,
            "chapters": chapters,
            "recent": recent,
            "volumes": volumes,
            "status_filter": status or "all",
            "status_options": STATUS_ORDER,
        },
    )


@router.post("/projects/{project}/meta")
def update_project_meta(
    request: Request,
    project: str,
    target_words: int = Form(100000),
    author: str = Form(""),
    synopsis: str = Form(""),
    daily_goal: int = Form(2000),
) -> Response:
    require_auth(request)
    safe_project = safe_slug(project, fallback="project")
    set_project_meta(safe_project, target_words, author, synopsis, daily_goal)
    log_operation("update_project_meta", safe_project)
    return RedirectResponse(url=f"/projects/{safe_project}", status_code=303)


@router.get("/projects/{project}/search", response_class=HTMLResponse)
def search_project(request: Request, project: str, q: str = "") -> Response:
    if not request.session.get("authed"):
        return RedirectResponse("/login", status_code=303)
    safe_project = safe_slug(project, fallback="project")
    results = []
    if q:
        escaped = q.replace('"', '""')
        with get_conn() as conn:
            # Query body or title
            rows = conn.execute(
                """
                SELECT path, title, snippet(chapter_fts, 4, '<mark class="bg-accent/20 text-accent px-0.5 rounded">', '</mark>', '...', 64) as excerpt
                FROM chapter_fts
                WHERE chapter_fts MATCH ? AND project = ?
                ORDER BY rank LIMIT 50
                """,
                (f'"{escaped}"', safe_project),
            ).fetchall()

            for r in rows:
                p = Path(r["path"])
                results.append(
                    {"filename": p.name, "title": r["title"], "excerpt": r["excerpt"]}
                )

    templates = get_templates()
    return templates.TemplateResponse(
        "search.html",
        {"request": request, "project": safe_project, "q": q, "results": results},
    )


@router.get("/projects/{project}/stats", response_class=HTMLResponse)
def project_stats(request: Request, project: str) -> Response:
    require_auth(request)
    safe_project = safe_slug(project, fallback="project")
    stats = get_project_stats(safe_project)
    templates = get_templates()
    return templates.TemplateResponse(
        "stats.html", {"request": request, "project": safe_project, "stats": stats}
    )
